/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const ValidatorError = t.iface([], {
  "field": "string",
  "message": "string",
});

export const ValidatorResult = t.iface([], {
  "error": "boolean",
  "detail": t.opt("ValidatorError"),
});

export const Member = t.iface([], {
  "_id": t.opt("string"),
  "_rev": t.opt("string"),
  "person_name": "string",
  "name": "string",
  "password": "string",
  "password_confirm": t.opt("string"),
  "phone": t.opt("string"),
  "email": "string",
});

export const Card = t.iface([], {
  "account_number": "string",
  "expiration_month": "number",
  "expiration_year": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  ValidatorError,
  ValidatorResult,
  Member,
  Card,
};
export default exportedTypeSuite;
